"""Initial migration

Revision ID: aedf9e3febcd
Revises: 
Create Date: 2025-12-20 15:16:24.482717+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedf9e3febcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('optimal_patterns', sa.JSON(), nullable=True),
    sa.Column('starter_code', sa.JSON(), nullable=True),
    sa.Column('reference_solution', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_difficulty'), 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    op.create_index(op.f('ix_problems_title'), 'problems', ['title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('PYTHON', 'JAVASCRIPT', name='programminglanguage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', name='submissionstatus'), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('all_tests_passed', sa.Boolean(), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('memory_kb', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_problem_id'), 'submissions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('weakness_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('error_frequency', sa.JSON(), nullable=False),
    sa.Column('ds_algo_weaknesses', sa.JSON(), nullable=False),
    sa.Column('complexity_trends', sa.JSON(), nullable=True),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('total_problems_solved', sa.Integer(), nullable=True),
    sa.Column('avg_attempts_per_problem', sa.Float(), nullable=True),
    sa.Column('improvement_velocity', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('top_weaknesses', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weakness_profiles_id'), 'weakness_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_weakness_profiles_user_id'), 'weakness_profiles', ['user_id'], unique=True)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('ast_features', sa.JSON(), nullable=True),
    sa.Column('estimated_time_complexity', sa.String(), nullable=True),
    sa.Column('estimated_space_complexity', sa.String(), nullable=True),
    sa.Column('optimal_time_complexity', sa.String(), nullable=True),
    sa.Column('optimal_space_complexity', sa.String(), nullable=True),
    sa.Column('complexity_match', sa.Float(), nullable=True),
    sa.Column('error_category', sa.Enum('INEFFICIENT_ALGORITHM', 'EDGE_CASE_MISSED', 'INCORRECT_DATA_STRUCTURE', 'OFF_BY_ONE', 'OVERFITTING_TO_EXAMPLES', 'POOR_ABSTRACTION', 'INCORRECT_LOGIC', 'MISSING_GUARD_CLAUSES', 'INEFFICIENT_SPACE_USAGE', 'INCORRECT_COMPLEXITY', 'RUNTIME_ERROR', 'TIMEOUT', 'MEMORY_LIMIT_EXCEEDED', name='errorcategory'), nullable=True),
    sa.Column('error_confidence', sa.Float(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_error_category'), 'analysis_results', ['error_category'], unique=False)
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_results_submission_id'), 'analysis_results', ['submission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_submission_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_error_category'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_weakness_profiles_user_id'), table_name='weakness_profiles')
    op.drop_index(op.f('ix_weakness_profiles_id'), table_name='weakness_profiles')
    op.drop_table('weakness_profiles')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_problem_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_problems_title'), table_name='problems')
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_difficulty'), table_name='problems')
    op.drop_table('problems')
    # ### end Alembic commands ###