"""add weak_tags, weak_patterns, analysis_metadata to weakness_profile

Revision ID: 25c8f3cf780c
Revises: 48419d58fc12
Create Date: 2025-12-25 10:53:33.544020+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c8f3cf780c'
down_revision = '48419d58fc12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weakness_profiles', sa.Column('weak_tags', sa.JSON(), nullable=True))
    op.add_column('weakness_profiles', sa.Column('weak_patterns', sa.JSON(), nullable=True))
    op.add_column('weakness_profiles', sa.Column('analysis_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weakness_profiles', 'analysis_metadata')
    op.drop_column('weakness_profiles', 'weak_patterns')
    op.drop_column('weakness_profiles', 'weak_tags')
    # ### end Alembic commands ###