"""downgr

Revision ID: 48419d58fc12
Revises: fe7887ad8798
Create Date: 2025-12-25 10:38:33.897821+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48419d58fc12'
down_revision = 'fe7887ad8798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###