"""update weakness profile

Revision ID: fe7887ad8798
Revises: 4e3e643a9704
Create Date: 2025-12-25 10:19:07.502151+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe7887ad8798'
down_revision = '4e3e643a9704'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weakness_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('weakness_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('weakness_profiles', 'error_frequency',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('weakness_profiles', 'ds_algo_weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('weakness_profiles', 'top_weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('weakness_profiles', 'weak_tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('weakness_profiles', 'weak_patterns',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index('ix_weakness_profiles_user_id', table_name='weakness_profiles')
    op.create_unique_constraint(None, 'weakness_profiles', ['user_id'])
    op.drop_constraint('weakness_profiles_user_id_fkey', 'weakness_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'weakness_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weakness_profiles', type_='foreignkey')
    op.create_foreign_key('weakness_profiles_user_id_fkey', 'weakness_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'weakness_profiles', type_='unique')
    op.create_index('ix_weakness_profiles_user_id', 'weakness_profiles', ['user_id'], unique=True)
    op.alter_column('weakness_profiles', 'weak_patterns',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weakness_profiles', 'weak_tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weakness_profiles', 'top_weaknesses',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('weakness_profiles', 'ds_algo_weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('weakness_profiles', 'error_frequency',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('weakness_profiles', 'updated_at')
    op.drop_column('weakness_profiles', 'created_at')
    # ### end Alembic commands ###