"""add weakness profile fields

Revision ID: 4e3e643a9704
Revises: aedf9e3febcd
Create Date: 2025-12-25 10:12:52.084499+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3e643a9704'
down_revision = 'aedf9e3febcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weakness_profiles', sa.Column('weak_tags', sa.JSON(), nullable=True))
    op.add_column('weakness_profiles', sa.Column('weak_patterns', sa.JSON(), nullable=True))
    op.add_column('weakness_profiles', sa.Column('analysis_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weakness_profiles', 'analysis_metadata')
    op.drop_column('weakness_profiles', 'weak_patterns')
    op.drop_column('weakness_profiles', 'weak_tags')
    # ### end Alembic commands ###